blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Nevermore1102/OpenCode_template#readme
  - name: Discussions
    url: https://github.com/Nevermore1102/OpenCode_template/discussions
